// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"

	users "github/internal/features/users"
)

// TokenUtilInterface is an autogenerated mock type for the TokenUtilInterface type
type TokenUtilInterface struct {
	mock.Mock
}

// DecodeToken provides a mock function with given fields: _a0
func (_m *TokenUtilInterface) DecodeToken(_a0 *jwt.Token) users.Users {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DecodeToken")
	}

	var r0 users.Users
	if rf, ok := ret.Get(0).(func(*jwt.Token) users.Users); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(users.Users)
	}

	return r0
}

// GenerateToken provides a mock function with given fields: _a0
func (_m *TokenUtilInterface) GenerateToken(_a0 users.Users) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(users.Users) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(users.Users) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(users.Users) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenUtilInterface creates a new instance of TokenUtilInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenUtilInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenUtilInterface {
	mock := &TokenUtilInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
