// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	todos "github/internal/features/todos"

	mock "github.com/stretchr/testify/mock"
)

// TQuery is an autogenerated mock type for the TQuery type
type TQuery struct {
	mock.Mock
}

// CreateTodo provides a mock function with given fields: _a0
func (_m *TQuery) CreateTodo(_a0 todos.Todos) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(todos.Todos) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTodo provides a mock function with given fields: _a0
func (_m *TQuery) DeleteTodo(_a0 uint) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadAllTodos provides a mock function with given fields: _a0
func (_m *TQuery) ReadAllTodos(_a0 uint) ([]todos.Todos, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ReadAllTodos")
	}

	var r0 []todos.Todos
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]todos.Todos, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uint) []todos.Todos); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]todos.Todos)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTodo provides a mock function with given fields: _a0, _a1
func (_m *TQuery) UpdateTodo(_a0 uint, _a1 todos.Todos) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, todos.Todos) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTQuery creates a new instance of TQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *TQuery {
	mock := &TQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
