// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	users "github/internal/features/users"

	mock "github.com/stretchr/testify/mock"
)

// UQuery is an autogenerated mock type for the UQuery type
type UQuery struct {
	mock.Mock
}

// Login provides a mock function with given fields: _a0
func (_m *UQuery) Login(_a0 string) (users.Users, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 users.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (users.Users, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) users.Users); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(users.Users)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: _a0
func (_m *UQuery) Register(_a0 users.Users) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(users.Users) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUQuery creates a new instance of UQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *UQuery {
	mock := &UQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
